name: figma_frame_inspector
description: A Flutter plugin to verify how accurately the Figma frame was implemented in the app.
version: 0.0.4
homepage: https://github.com/amatkivskiy/figma-frame-inspector 

environment:
  sdk: ">=2.16.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.2.1
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: