name: figma_frame_inspector
description: A Flutter plugin to verify how accurately the Figma frame was implemented in the app.
version: 0.0.1
homepage: https://github.com/amatkivskiy/figma-frame-inspector 

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  cached_network_image: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: